export const ACTION_TYPES = {
  LOGIN_STARTED: "LOGIN_STARTED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_RESET: "LOGIN_RESET",
  LOGIN_ERROR: "LOGIN_ERROR",

  UN_AUTH_ERROR: "UN_AUTH_ERROR",

  SIGNUP_STARTED: "SIGNUP_STARTED",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_RESET: "SIGNUP_RESET",
  SIGNUP_ERROR: "SIGNUP_ERROR",

  TODAY_ATTEMPT_STARTED: "TODAY_ATTEMPT_STARTED",
  TODAY_ATTEMPT_SUCCESS: "TODAY_ATTEMPT_SUCCESS",
  TODAY_ATTEMPT_RESET: "TODAY_ATTEMPT_RESET",
  TODAY_ATTEMPT_ERROR: "TODAY_ATTEMPT_ERROR",

  HIGH_SCORE_STARTED: "HIGH_SCORE_STARTED",
  HIGH_SCORE_SUCCESS: "HIGH_SCORE_SUCCESS",
  HIGH_SCORE_RESET: "HIGH_SCORE_RESET",
  HIGH_SCORE_ERROR: "HIGH_SCORE_ERROR",

  SAVE_SCORE_STARTED: "SAVE_SCORE_STARTED",
  SAVE_SCORE_SUCCESS: "SAVE_SCORE_SUCCESS",
  SAVE_SCORE_RESET: "SAVE_SCORE_RESET",
  SAVE_SCORE_ERROR: "SAVE_SCORE_ERROR",
};

export const SAGA_ACTIONS = {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  TODAY_ATTEMPT: "TODAY_ATTEMPT",
  HIGH_SCORE: "HIGH_SCORE",
  SAVE_SCORE: "SAVE_SCORE",
};

export const API_END_POINTS = {
  LOGIN: "/api/auth/login",
  SIGNUP: "/api/auth/signup",
  TODAY_ATTEMPT: "/api/todayScores",
  HIGH_SCORE: "/api/highScore",
  SAVE_SCORE: "/api/score",
};
